formulas = {"N'hésitez pas à me solliciter, je suis à votre disposition": "#inform",
            "Bonjour et bienvenue chez": "#greeting",
            "Votre satisfaction est notre priorité": "#closing_politeness_statement",
            "votre code postal et localité": "#request",
            "nom et prénom": "#request",
            "bienvenue chez ": "#greeting",
            "prendre votre carte grise": "#request",
            "à titre particulier ou professionnel": "#choice_question",
            "ienvenue chez": "#greeting",
            "nous confier votre": "#request",
            "vous convient ou": "#choice_question",
            "prendra contact avec vous": "#inform",
            "j’ouvre votre dossier": "#dialog_act_invitation",
            "besoin d’éléments complémentaires": "#dialog_act_invitation",
            "financer votre achat": "#request",
            "confier votre": "#request", "Bonsoir": "#greeting",
            "je suis à votre disposition": "#closing_politeness_statement",
            "onjour": "#greeting",
            "puis je vous aider": "#elicitation",
            "Visitor uploaded:": "#upload",
            "vous faire contacter par un conseiller": "#confirm",
            "Bonne soirée": "#closing_greeting",
            "à votre service": "#closing_politeness_statement",
            "vous remercie pour ces informations": "#thanking",
            "bonne soiree": "#closing_greeting",
            "Cela vous convient-il": "#choice_question",
            "#une préférence pour": "#choice_question",
            "prendre votre carte grise en photo": "#request",
            "demander si vous hésitez": "#request",
            "Je vous souhaite": "#closing_politeness_statement",
            "demander votre profession": "#request",
            "Non nous ren": "#threat",
            "vous souhaite une bonne": "#closing_politeness_statement",
            "vous souhaite un bon": "#closing_politeness_statement",
            "notre gamme vous intéresse": "#request",
            "puis-je faire pour vous": "#dialog_act_invitation",
            "vais prendre les informations concernant votre projet": "#dialog_act_invitation",
            "Pour une estimation de votre véhicule, j’ai besoin": "#dialog_act_invitation",
            "votre kilométrage annuel": "#request",
            "vous remercie": "#thanking",
            "une préférence pour la boite de vitesses": "#set_question",
            "budget mensuel": "#request", "bonne journée": "#closing_politeness_statement",
            "indiquer votre numéro d’immatriculation": "#request",
            "Souhaitez vous": "#request",
            "Votre projet": "#set_question",
            "mise en relation avec notre conseiller fiscal": "#dialog_act_invitation",
            "la raison sociale de votre entreprise": "#request",
            "une mise en relation avec": "#choice_question",
            "pourrait vous convenir": "#choice_question",
            "onne soirée": "#closing_greeting",
            "Agent uploaded": "#upload",
            "[Bb]ienvenue": "#greeting",
            "Bienvenue chez ": "#greeting",
            "vous demander vos nom et prénom": "#request",
            "je vous invite à patienter": "#pausing", "présentation vidéo live du véhicule": "#dialog_act_invitation",
            "permet de prendre la photo instantanément": "#photo",
            "noter cet échange": "#note",
            "http": "#url",
            "www": "#url", "jpeg": "#upload"}